"""Tickets ORM models.

Tables:
- `tickets`         — the support ticket itself (one row per issue)
- `ticket_comments` — threaded comments / timeline events on a ticket

Tickets are NOT tenant-scoped (no RLS): they are visible to anyone
with `support` access on the platform admin dashboard. `agency_id`
is recorded for filtering but is nullable for cross-tenant issues.

Files / attachments are intentionally out of scope for v1 — the UI
shows the attachment column as a count ("3") derived from
`ticket_comments` rows of kind `ATTACHMENT`. If we ever need real
file uploads we'll add S3 (or Supabase Storage) wiring and a separate
`ticket_attachments` table.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    Index,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.shared.domain.base_entity import Base, IdMixin, TimestampedMixin
from src.shared.domain.enum_mapping import pg_name
from src.shared.domain.enums import TicketCommentKind, TicketPriority, TicketStatus

if TYPE_CHECKING:
    from src.modules.agencies.models import Agency
    from src.modules.identity.models import User


class Ticket(IdMixin, TimestampedMixin, Base):
    """An internal admin support ticket.

    `code` is the human-friendly identifier shown in the dashboard
    (e.g. `TK-2847`). It's NOT the primary key — `id` is. `code`
    is generated by the service layer on create, padded to 4 digits
    from a per-day sequence so it's monotonically increasing within
    a single day and easy to scan visually.
    """

    __tablename__ = "tickets"

    # Human-friendly identifier (TK-0001).
    code: Mapped[str] = mapped_column(String(32), nullable=False, unique=True)

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    status: Mapped[TicketStatus] = mapped_column(
        Enum(
            TicketStatus,
            name=pg_name(TicketStatus),
            values_callable=lambda enum_cls: [m.value for m in enum_cls],
        ),
        nullable=False,
        default=TicketStatus.OPEN,
        server_default=TicketStatus.OPEN.value,
        index=True,
    )
    priority: Mapped[TicketPriority] = mapped_column(
        Enum(
            TicketPriority,
            name=pg_name(TicketPriority),
            values_callable=lambda enum_cls: [m.value for m in enum_cls],
        ),
        nullable=False,
        default=TicketPriority.MEDIUM,
        server_default=TicketPriority.MEDIUM.value,
        index=True,
    )

    # NULL = cross-tenant ticket (no specific agency).
    agency_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    reporter_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    assignee_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Soft delete: tickets are never hard-deleted. The dashboard
    # filters them out by default; `?include_deleted=true` shows them.
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Free-form bag for the dashboard to attach context (e.g. the URL
    # of a related audit-log entry, last activity timestamps, etc).
    # Reserved for future use — current UI doesn't read it.
    extra: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict, server_default=text("'{}'::jsonb")
    )

    comments: Mapped[list["TicketComment"]] = relationship(
        back_populates="ticket",
        cascade="all, delete-orphan",
        order_by="TicketComment.created_at",
    )

    __table_args__ = (
        Index("idx_tickets_status_priority", "status", "priority"),
        Index("idx_tickets_created_at", "created_at"),
    )


class TicketComment(IdMixin, TimestampedMixin, Base):
    """A comment or timeline event on a ticket.

    We collapse what other systems split into `comments` /
    `ticket_events` into one table because the volume is low and the
    dashboard renders them as a single chronological feed.
    """

    __tablename__ = "ticket_comments"

    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tickets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    author_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )

    kind: Mapped[TicketCommentKind] = mapped_column(
        Enum(
            TicketCommentKind,
            name=pg_name(TicketCommentKind),
            values_callable=lambda enum_cls: [m.value for m in enum_cls],
        ),
        nullable=False,
        default=TicketCommentKind.COMMENT,
        server_default=TicketCommentKind.COMMENT.value,
    )

    body: Mapped[str] = mapped_column(Text, nullable=False)

    # Optional metadata — e.g. {"from": "OPEN", "to": "IN_PROGRESS"}
    # for STATUS_CHANGE rows. JSONB so the schema doesn't need to
    # change when we add new event flavours.
    event_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
    )

    # Comments are usually not edited; expose a flag for the rare
    # "fix typo" case without needing a separate table.
    edited_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    ticket: Mapped["Ticket"] = relationship(back_populates="comments")

    __table_args__ = (
        Index("idx_ticket_comments_ticket_created", "ticket_id", "created_at"),
    )


__all__ = ["Ticket", "TicketComment", "TicketCommentKind"]